language: bash
services:
  - docker

# Build the image, run it in background, curl the port, stop the container.
script:
  - docker build -t pypiserver .
  - docker run -d --name pypiserver -p 8080:8080 pypiserver
  - sleep 5
  - curl -L localhost:8080
  - docker stop pypiserver
